set(_CATKIN_CURRENT_PACKAGE "ucar_nav")
set(ucar_nav_VERSION "0.0.0")
set(ucar_nav_MAINTAINER "lijixiang <lijixiang@todo.todo>")
set(ucar_nav_PACKAGE_FORMAT "2")
set(ucar_nav_BUILD_DEPENDS "nav_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "message_generation")
set(ucar_nav_BUILD_EXPORT_DEPENDS "nav_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs")
set(ucar_nav_BUILDTOOL_DEPENDS "catkin")
set(ucar_nav_BUILDTOOL_EXPORT_DEPENDS )
set(ucar_nav_EXEC_DEPENDS "nav_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "message_runtime")
set(ucar_nav_RUN_DEPENDS "nav_msgs" "roscpp" "rospy" "sensor_msgs" "std_msgs" "message_runtime")
set(ucar_nav_TEST_DEPENDS )
set(ucar_nav_DOC_DEPENDS )
set(ucar_nav_URL_WEBSITE "")
set(ucar_nav_URL_BUGTRACKER "")
set(ucar_nav_URL_REPOSITORY "")
set(ucar_nav_DEPRECATED "")