(cl:in-package unitree_legged_msgs-msg)
(cl:export '(LEVELFLAG-VAL
          LEVELFLAG
          COMMVERSION-VAL
          COMMVERSION
          ROBOTID-VAL
          ROBOTID
          SN-VAL
          SN
          BANDWIDTH-VAL
          BANDWIDTH
          MODE-VAL
          MODE
          IMU-VAL
          IMU
          POSITION-VAL
          POSITION
          VELOCITY-VAL
          VELOCITY
          YAWSPEED-VAL
          YAWSPEED
          FOOTPOSITION2BODY-VAL
          FOOTPOSITION2BODY
          FOOTSPEED2BODY-VAL
          FOOTSPEED2BODY
          FOOTFORCE-VAL
          FOOTFORCE
          WIRELESSREMOTE-VAL
          WIRELESSREMOTE
          RESERVE-VAL
          RESERVE
          CRC-VAL
          CRC
))