(cl:in-package unitree_legged_msgs-msg)
(cl:export '(LEVELFLAG-VAL
          LEVELFLAG
          COMMVERSION-VAL
          COMMVERSION
          ROBOTID-VAL
          ROBOTID
          SN-VAL
          SN
          BANDWIDTH-VAL
          BANDWIDTH
          MODE-VAL
          MODE
          GAITTYPE-VAL
          GAITTYPE
          SPEEDLEVEL-VAL
          SPEEDLEVEL
          DFOOTRAISEHEIGHT-VAL
          DFOOTRAISEHEIGHT
          DBODYHEIGHT-VAL
          DBODYHEIGHT
          POSITION-VAL
          POSITION
          RPY-VAL
          RPY
          VELOCITY-VAL
          VELOCITY
          YAWSPEED-VAL
          YAWSPEED
          LED-VAL
          LED
          WIRELESSREMOTE-VAL
          WIRELESSREMOTE
          RESERVE-VAL
          RESERVE
          CRC-VAL
          CRC
))