# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from unitree_legged_msgs/HighCmd.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import unitree_legged_msgs.msg

class HighCmd(genpy.Message):
  _md5sum = "59333cac6112fd0a7a3d3c5b564af567"
  _type = "unitree_legged_msgs/HighCmd"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint8 levelFlag
uint16 commVersion
uint16 robotID
uint32 SN
uint8 bandWidth
uint8 mode 
uint8 gaitType		   
uint8 speedLevel	
float32 dFootRaiseHeight		   
float32 dBodyHeight	 
float32[2] position 
float32[3] rpy	   
float32[2] velocity 
float32 yawSpeed		   
LED[4] led
uint8[40] wirelessRemote
uint32 reserve
uint32 crc
================================================================================
MSG: unitree_legged_msgs/LED
uint8 r
uint8 g
uint8 b"""
  __slots__ = ['levelFlag','commVersion','robotID','SN','bandWidth','mode','gaitType','speedLevel','dFootRaiseHeight','dBodyHeight','position','rpy','velocity','yawSpeed','led','wirelessRemote','reserve','crc']
  _slot_types = ['uint8','uint16','uint16','uint32','uint8','uint8','uint8','uint8','float32','float32','float32[2]','float32[3]','float32[2]','float32','unitree_legged_msgs/LED[4]','uint8[40]','uint32','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       levelFlag,commVersion,robotID,SN,bandWidth,mode,gaitType,speedLevel,dFootRaiseHeight,dBodyHeight,position,rpy,velocity,yawSpeed,led,wirelessRemote,reserve,crc

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(HighCmd, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.levelFlag is None:
        self.levelFlag = 0
      if self.commVersion is None:
        self.commVersion = 0
      if self.robotID is None:
        self.robotID = 0
      if self.SN is None:
        self.SN = 0
      if self.bandWidth is None:
        self.bandWidth = 0
      if self.mode is None:
        self.mode = 0
      if self.gaitType is None:
        self.gaitType = 0
      if self.speedLevel is None:
        self.speedLevel = 0
      if self.dFootRaiseHeight is None:
        self.dFootRaiseHeight = 0.
      if self.dBodyHeight is None:
        self.dBodyHeight = 0.
      if self.position is None:
        self.position = [0.] * 2
      if self.rpy is None:
        self.rpy = [0.] * 3
      if self.velocity is None:
        self.velocity = [0.] * 2
      if self.yawSpeed is None:
        self.yawSpeed = 0.
      if self.led is None:
        self.led = [unitree_legged_msgs.msg.LED() for _ in range(4)]
      if self.wirelessRemote is None:
        self.wirelessRemote = b'\0'*40
      if self.reserve is None:
        self.reserve = 0
      if self.crc is None:
        self.crc = 0
    else:
      self.levelFlag = 0
      self.commVersion = 0
      self.robotID = 0
      self.SN = 0
      self.bandWidth = 0
      self.mode = 0
      self.gaitType = 0
      self.speedLevel = 0
      self.dFootRaiseHeight = 0.
      self.dBodyHeight = 0.
      self.position = [0.] * 2
      self.rpy = [0.] * 3
      self.velocity = [0.] * 2
      self.yawSpeed = 0.
      self.led = [unitree_legged_msgs.msg.LED() for _ in range(4)]
      self.wirelessRemote = b'\0'*40
      self.reserve = 0
      self.crc = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B2HI4B2f().pack(_x.levelFlag, _x.commVersion, _x.robotID, _x.SN, _x.bandWidth, _x.mode, _x.gaitType, _x.speedLevel, _x.dFootRaiseHeight, _x.dBodyHeight))
      buff.write(_get_struct_2f().pack(*self.position))
      buff.write(_get_struct_3f().pack(*self.rpy))
      buff.write(_get_struct_2f().pack(*self.velocity))
      _x = self.yawSpeed
      buff.write(_get_struct_f().pack(_x))
      if len(self.led) != 4:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (4, len(self.led), 'self.led')))
      for val1 in self.led:
        _x = val1
        buff.write(_get_struct_3B().pack(_x.r, _x.g, _x.b))
      _x = self.wirelessRemote
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_40B().pack(*_x))
      else:
        buff.write(_get_struct_40s().pack(_x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.reserve, _x.crc))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.led is None:
        self.led = None
      end = 0
      _x = self
      start = end
      end += 21
      (_x.levelFlag, _x.commVersion, _x.robotID, _x.SN, _x.bandWidth, _x.mode, _x.gaitType, _x.speedLevel, _x.dFootRaiseHeight, _x.dBodyHeight,) = _get_struct_B2HI4B2f().unpack(str[start:end])
      start = end
      end += 8
      self.position = _get_struct_2f().unpack(str[start:end])
      start = end
      end += 12
      self.rpy = _get_struct_3f().unpack(str[start:end])
      start = end
      end += 8
      self.velocity = _get_struct_2f().unpack(str[start:end])
      start = end
      end += 4
      (self.yawSpeed,) = _get_struct_f().unpack(str[start:end])
      self.led = []
      for i in range(0, 4):
        val1 = unitree_legged_msgs.msg.LED()
        _x = val1
        start = end
        end += 3
        (_x.r, _x.g, _x.b,) = _get_struct_3B().unpack(str[start:end])
        self.led.append(val1)
      start = end
      end += 40
      self.wirelessRemote = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.reserve, _x.crc,) = _get_struct_2I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B2HI4B2f().pack(_x.levelFlag, _x.commVersion, _x.robotID, _x.SN, _x.bandWidth, _x.mode, _x.gaitType, _x.speedLevel, _x.dFootRaiseHeight, _x.dBodyHeight))
      buff.write(self.position.tostring())
      buff.write(self.rpy.tostring())
      buff.write(self.velocity.tostring())
      _x = self.yawSpeed
      buff.write(_get_struct_f().pack(_x))
      if len(self.led) != 4:
        self._check_types(ValueError("Expecting %s items but found %s when writing '%s'" % (4, len(self.led), 'self.led')))
      for val1 in self.led:
        _x = val1
        buff.write(_get_struct_3B().pack(_x.r, _x.g, _x.b))
      _x = self.wirelessRemote
      # - if encoded as a list instead, serialize as bytes instead of string
      if type(_x) in [list, tuple]:
        buff.write(_get_struct_40B().pack(*_x))
      else:
        buff.write(_get_struct_40s().pack(_x))
      _x = self
      buff.write(_get_struct_2I().pack(_x.reserve, _x.crc))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.led is None:
        self.led = None
      end = 0
      _x = self
      start = end
      end += 21
      (_x.levelFlag, _x.commVersion, _x.robotID, _x.SN, _x.bandWidth, _x.mode, _x.gaitType, _x.speedLevel, _x.dFootRaiseHeight, _x.dBodyHeight,) = _get_struct_B2HI4B2f().unpack(str[start:end])
      start = end
      end += 8
      self.position = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=2)
      start = end
      end += 12
      self.rpy = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=3)
      start = end
      end += 8
      self.velocity = numpy.frombuffer(str[start:end], dtype=numpy.float32, count=2)
      start = end
      end += 4
      (self.yawSpeed,) = _get_struct_f().unpack(str[start:end])
      self.led = []
      for i in range(0, 4):
        val1 = unitree_legged_msgs.msg.LED()
        _x = val1
        start = end
        end += 3
        (_x.r, _x.g, _x.b,) = _get_struct_3B().unpack(str[start:end])
        self.led.append(val1)
      start = end
      end += 40
      self.wirelessRemote = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.reserve, _x.crc,) = _get_struct_2I().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2I = None
def _get_struct_2I():
    global _struct_2I
    if _struct_2I is None:
        _struct_2I = struct.Struct("<2I")
    return _struct_2I
_struct_2f = None
def _get_struct_2f():
    global _struct_2f
    if _struct_2f is None:
        _struct_2f = struct.Struct("<2f")
    return _struct_2f
_struct_3B = None
def _get_struct_3B():
    global _struct_3B
    if _struct_3B is None:
        _struct_3B = struct.Struct("<3B")
    return _struct_3B
_struct_3f = None
def _get_struct_3f():
    global _struct_3f
    if _struct_3f is None:
        _struct_3f = struct.Struct("<3f")
    return _struct_3f
_struct_40B = None
def _get_struct_40B():
    global _struct_40B
    if _struct_40B is None:
        _struct_40B = struct.Struct("<40B")
    return _struct_40B
_struct_40s = None
def _get_struct_40s():
    global _struct_40s
    if _struct_40s is None:
        _struct_40s = struct.Struct("<40s")
    return _struct_40s
_struct_B2HI4B2f = None
def _get_struct_B2HI4B2f():
    global _struct_B2HI4B2f
    if _struct_B2HI4B2f is None:
        _struct_B2HI4B2f = struct.Struct("<B2HI4B2f")
    return _struct_B2HI4B2f
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
