// Generated by gencpp from file ucar_nav/Boxinfo.msg
// DO NOT EDIT!


#ifndef UCAR_NAV_MESSAGE_BOXINFO_H
#define UCAR_NAV_MESSAGE_BOXINFO_H

#include <ros/service_traits.h>


#include <ucar_nav/BoxinfoRequest.h>
#include <ucar_nav/BoxinfoResponse.h>


namespace ucar_nav
{

struct Boxinfo
{

typedef BoxinfoRequest Request;
typedef BoxinfoResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Boxinfo
} // namespace ucar_nav


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ucar_nav::Boxinfo > {
  static const char* value()
  {
    return "dc4ccb29fbc5c9e5a5b7a5542979e09e";
  }

  static const char* value(const ::ucar_nav::Boxinfo&) { return value(); }
};

template<>
struct DataType< ::ucar_nav::Boxinfo > {
  static const char* value()
  {
    return "ucar_nav/Boxinfo";
  }

  static const char* value(const ::ucar_nav::Boxinfo&) { return value(); }
};


// service_traits::MD5Sum< ::ucar_nav::BoxinfoRequest> should match
// service_traits::MD5Sum< ::ucar_nav::Boxinfo >
template<>
struct MD5Sum< ::ucar_nav::BoxinfoRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ucar_nav::Boxinfo >::value();
  }
  static const char* value(const ::ucar_nav::BoxinfoRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ucar_nav::BoxinfoRequest> should match
// service_traits::DataType< ::ucar_nav::Boxinfo >
template<>
struct DataType< ::ucar_nav::BoxinfoRequest>
{
  static const char* value()
  {
    return DataType< ::ucar_nav::Boxinfo >::value();
  }
  static const char* value(const ::ucar_nav::BoxinfoRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ucar_nav::BoxinfoResponse> should match
// service_traits::MD5Sum< ::ucar_nav::Boxinfo >
template<>
struct MD5Sum< ::ucar_nav::BoxinfoResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ucar_nav::Boxinfo >::value();
  }
  static const char* value(const ::ucar_nav::BoxinfoResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ucar_nav::BoxinfoResponse> should match
// service_traits::DataType< ::ucar_nav::Boxinfo >
template<>
struct DataType< ::ucar_nav::BoxinfoResponse>
{
  static const char* value()
  {
    return DataType< ::ucar_nav::Boxinfo >::value();
  }
  static const char* value(const ::ucar_nav::BoxinfoResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UCAR_NAV_MESSAGE_BOXINFO_H
