obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.34, -0.11], [-0.34, -0.11], [-0.34, 0.11], [0.34, 0.11]]
inflation_radius: 0.13

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: camera_depth_frame, data_type: LaserScan, topic: /scan, marking: true, clearing: true}