# 本地规划代价地图配置文件  
local_costmap:
   global_frame: map # 参数定义了代价地图应该运行的坐标系
   robot_base_frame: base_link # 参数定义了代价地图应该为机器人的基座的坐标系。
   update_frequency: 10.0 # 参数决定了代价地图更新的频率（以Hz为单位）。
   publish_frequency: 10.0 # 参数决定代价地图发布可视化信息的速率（以Hz为单位）。
   #static_map: false # 参数确定是否由map_server提供的地图服务来进行代价地图的初始化。
   static_map: false
   rolling_window: true # 参数设置为true意味着当机器人移动时，保持机器人在本地代价地图中心。
   width: 1.5 # 代价地图宽度
   height: 1.5 # 代价地图高度
   resolution: 0.02 #代价地图分辨率（米/单元格）
   transform_tolerance: 5
   plugins:
    - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}